### PR TITLE
fix: Add trim and scoped postcss plugins at the start of plugin list

### PR DESCRIPTION
**Pull request by znck**
fixes #30

### CODE REVIEW

**Comment by znck** [comment]
Now `trim` and `scoped` plugins are added at the start of the plugins list, before any user defined plugins. Just to be sure, I'll add a test so it won't break.

**Comment by JounQin** [comment]
There is no `user defined plugins` at all when using `vue-loader` because `.scss` files are handled by `sass-loader` and `postcss-loader` then it will be transformed into pure `.css` and no `postcss` plugins will be passed into `compileStyle` function.

You can check https://github.com/vuejs/vue-loader/blob/master/lib/loaders/pitcher.js#L92-L105 and https://github.com/vuejs/vue-loader/blob/master/lib/loaders/stylePostLoader.js

**Comment by trainiac** [comment]
@znck is there something holding up a release of this fix?

**Comment by znck** [comment]
I am waiting for @yyx990803's take on this.

**Pull request merged**
