### PR TITLE
fix: default parser was removed from prettier

### PR DESCRIPTION
**Pull request by pwang2**
see https://github.com/prettier/prettier/issues/4567

### CODE REVIEW

**Comment by yyx990803** [comment]
@lovemyliwu it's Sunday in US, and open source developers also have a life.

**Comment by rof20004** [comment]
Well, I will take some coffee and wait! 

:)

**Comment by lafeer** [comment]
so what needs to be done to fix this?

**Comment by iidear** [comment]
@lafeer `npm i prettier@~1.12.0`

**Comment by lafeer** [comment]
I still get this :/

ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-4099cde5","hasScoped":false,"optionsId":"0","buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./web/src/js/components/Tabs.vue
Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/builds/frontend/xy-cms/node_modules/prettier/index.js:7051:13)
    at formatWithCursor (/builds/frontend/xy-cms/node_modules/prettier/index.js:10370:12)
    at /builds/frontend/xy-cms/node_modules/prettier/index.js:31115:15
    at Object.format (/builds/frontend/xy-cms/node_modules/prettier/index.js:31134:12)
    at Object.module.exports (/builds/frontend/xy-cms/node_modules/vue-loader/lib/template-compiler/index.js:73:23)
 @ ./web/src/js/components/Tabs.vue 6:0-333
 @ ./web/src/main.js

**Pull request merged**
