### PR TITLE
chore: move vue-template-compiler to peerDependencies

### LINKED ISSUE #11: Dependency on vue-template-compiler
The component-compiler-utils module requires vue-template-compiler, but it's not listed as a dependency (only a dev dependency). When I use vue-loader with a custom template compiler, and I don't install vue-template-compiler, I get an error.

Of course as a workaround I can install vue-template-compiler manually. But in that case I end up having three template compilers installed: vue-template-compiler, vue-template-es2015-compiler and my custom template compiler. Is that intentional?

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Fix #11

### CODE REVIEW

**Comment by znck** [comment]
Do not remove from devDependencies. Just add a peerDependecy and put * as version.

**Comment by ishitatsuyuki** [comment]
@znck done.

**Comment by yyx990803** [comment]
FYI I reverted this in 2.0.0. See [here](https://github.com/vuejs/component-compiler-utils#why-isnt-vue-template-compiler-a-peerdependency)

In 2.0.0 the compiler must be passed via options in `parse` as well.

**Comment by znck** [comment]
Oh! Should I revert this?

**Pull request merged**
